Do not rely on ansible inventory for upgrading non controller nodes
Currently we are relying on the ansible inventory to provide groups
containing compute nodes and their facts when creating the upgrade
scripts. In order to remove this requirement and provide easier
integration this change discovers the compute and swift storage nodes
from the undercloud. In addition it adds a wait loop for instance live
migration to complete before and after upgrading compute nodes and adds
support for swift storage nodes upgrade.

Change-Id: Ia4b2e81845c3fec9036c4695f0dd1746d4c5c6b8

diff --git a/templates/node_upgrade_pre.sh.j2 b/templates/node_upgrade_pre.sh.j2
--- a/templates/node_upgrade_pre.sh.j2
+++ b/templates/node_upgrade_pre.sh.j2
@@ -1,2 +1,17 @@
 source {{ overcloud_rc }}
-nova host-evacuate-live {{ hostvars[node_name].ansible_fqdn }}
+nova host-evacuate-live {{ node_name }}
+
+timeout_seconds=120
+elapsed_seconds=0
+while true; do
+    INSTANCE_COUNT=$(openstack server list --host {{ node_name }} -f json | jq -r -c '[.[] | select(.Status | contains("ACTIVE") or contains("PAUSED"))] | length')
+    if [ $INSTANCE_COUNT == 0 ]; then
+        break
+    fi
+    sleep 3
+    (( elapsed_seconds += 3 ))
+    if [ $elapsed_seconds -ge $timeout_seconds ]; then
+        echo "FAILURE: Could not quiesce compute node {{ node_name }}"
+    exit 1
+    fi
+done
